# Generated by Django 3.2.25 on 2024-10-21 14:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_auto_20241021_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcode',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 14, 16, 50, 59831, tzinfo=utc)),
        ),
    ]
